console.log("---------------------------------------");
let name=("|Ｎａｍｅ ＝ Ａｒｐｉｔ"+"               |");
let school=("|School = Central India Academy"+"       |");
let grade=("|Grade = A"+"                            |");
let section=("|Section = B"+"                          |");
let rollno=("|Roll No. = 199"+"                       |");
console.log(name);
console.log(school);
console.log(grade);
console.log(section);
console.log(rollno);
console.log("--------------Marks Scord--------------");
let java=("Java = 70");
let Dsa=("DSA = 65");
let Python=("Python = 75");
console.log(java,Dsa,Python);
